### ISSUE TITLE
Error in package installation with pandas==1.4.2

### ISSUE THREAD

**Issue by nguye2tl** [edwinnglabs/karpiu#43]
Hi Edwin,
Happy Holidays! Incredible work here. Thank you so much for sharing such an impressive modeling work. I have been trying to start testing the model and I keep running into issues with pandas==1.4.2. I followed your instructions, and I hope you don't mind helping me. pystan==2.19.1.1 requires python<3.8 so I install python 3.7. Does Karpiu use python 3.8 because no matter how many times that I tried, I couldn't install Karpiu

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/88795214/210011912-e84c1294-d780-42c3-bd11-3a5d1370ef46.png">
 Did you run into any issues with the python conflicts? Sorry for the question. I appreciate your help very much and I hope to hear back from you. Thank you so much!

**Comment by edwinnglabs** [comment]
Maybe you can try Python 3.8? It seems my [workflow](https://github.com/edwinnglabs/karpiu/blob/main/.github/workflows/build.yaml) only test on Python 3.8 right now.  And there will be a better solution upcoming by using `cmdstanpy` in the upstream package `orbit-ml` once the [PR](https://github.com/uber/orbit/pulls) is done.

**Comment by edwinnglabs** [comment]
And appreciate your attention of this super early work.

**Comment by edwinnglabs** [comment]
@nguye2tl a new version just pushed and is using `cmdstanpy` in the backend now
