### ISSUE TITLE
Update Installation in Tutorial Pages

### ISSUE THREAD

**Issue by edwinnglabs** [edwinnglabs/karpiu#49]

**Comment by kacper-sellforte** [comment]
Do I understand correctly that now Pystan is no longer required and cmdstan is used as a backend as that's what Orbit uses?

**Comment by edwinnglabs** [comment]
@kacper-sellforte  you are right. PyStan is a archived project so we need to move on to cmdstanpy asap and hopefully smoothly transited in next version.
