### ISSUE TITLE
Code execution error when running Karpiu from local jupyter notebook

### ISSUE THREAD

**Issue by nguye2tl** [edwinnglabs/karpiu#51]
Hi Edwin,
Thank you so much for answering my questions about how to install the Karpiu. Greatly appreciate that you share with the public about your work development. I am able to figure it out and to start testing the file. However, I am running into the issue with the first step of creating data in the data_creation notebook: 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/88795214/216427987-3e369227-5990-42da-8261-127c2c650194.png">
I understand your busy schedule and I am sorry for reaching out to ask for help and clarification. I am truly fascinated by the work that you have built so far and I would love to be able to run it and to learn from it.
Once again, appreciate your help and your time very much.

**Comment by edwinnglabs** [comment]
> Hi Edwin, Thank you so much for answering my questions about how to install the Karpiu. Greatly appreciate that you share with the public about your work development. I am able to figure it out and to start testing the file. However, I am running into the issue with the first step of creating data in the data_creation notebook: <img alt="image" width="696" src="https://user-images.githubusercontent.com/88795214/216427987-3e369227-5990-42da-8261-127c2c650194.png"> I understand your busy schedule and I am sorry for reaching out to ask for help and clarification. I am truly fascinated by the work that you have built so far and I would love to be able to run it and to learn from it. Once again, appreciate your help and your time very much.

Thanks for asking this. The current function `make_mmm_daily_data` has been updated to return three outputs. Feel free to take a look [here](https://github.com/edwinnglabs/karpiu/blob/main/karpiu/simulation.py#L188).

**Comment by edwinnglabs** [comment]
The doc will probably be updated next version when i have more unit tests up running.

**Comment by nguye2tl** [comment]
Hi Edwin,

Thank you so much for getting back and answering my questions. I truly appreciate it, as I understand your busy work schedule. When I run into the issue, I thought it came from a function that only returns a single value, and I tried to unpack the return value into two variables. So I thought it got to do with how scalability_df was created. Using your updated code, I am able to run it now. Appreciate it very much.
I have two more questions:
1. Scalability: The concept of scalability is a bit new to me. For general rule of thumb, do you assign scalability based on the media spend or coefficients?
2. Adstock matrix and adstock_df: Your definition of make_adstock_matrix, and adstock process for me. Just want to ask a quick question about whether I would need to transform an array to a data frame? 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/88795214/220197859-da743af6-edda-4fe1-b393-261e32e214f7.png">
What I am trying to do is to find a way to follow your steps in the quickstart notebook here: 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/88795214/220197968-bb47ef18-9e01-41e6-8962-e943a6f496f7.png">
Do you think I am running the steps correctly? Since I don't have the raw data, I am just trying to follow your docs to make sure I am not making any mistakes. Apologies for my novice coding skill here.
3. Daily data vs. weekly data for pystan: Do you run into any performance issue with pystan using daily data?
Sorry for all the questions. Greatly appreciate your time answering my questions. You are truly the best, Edwin.
Thank you,
Lan Nguyen

**Comment by nguye2tl** [comment]
Hi Edwin,
Just want to say how incredibly brilliant your work is! All of the improvements with seasonality and non seasonality and events are just genius and impressive. I just run out of words to compliment how great your work is. I am able to run the jupyter notebook and understand the flow of your logic. Just absolutely brilliant! Thank you so much for sharing this work and allowing analytics professional like me to learn from a great mind like you.
If I want to test a different marketing dataset, I probably need to run adstock process and scalability separately then. I am still working through that but want to say I greatly appreciate this valuable opportunity to learn.
Thank you,
Lan Nguyen

**Comment by nguye2tl** [comment]
Hi Edwin,
Sorry for another question, I am testing Karipu in both google colab and jupyter notebook. I am able to install karpiu via git but I keep running into dlt.exe issue. I have followed all the installation step accordingly and I am not sure what is the best way to fix it. Do I have to re-install the package every time I want to work on jupyter notebook?
![image](https://user-images.githubusercontent.com/88795214/222851050-0610ef68-60de-482d-855f-0c29bd3adab1.png)
Thank you so much for your guidance! 
Lan Nguyen

**Comment by edwinnglabs** [comment]
> Hi Edwin, Sorry for another question, I am testing Karipu in both google colab and jupyter notebook. I am able to install karpiu via git but I keep running into dlt.exe issue. I have followed all the installation step accordingly and I am not sure what is the best way to fix it. Do I have to re-install the package every time I want to work on jupyter notebook? ![image](https://user-images.githubusercontent.com/88795214/222851050-0610ef68-60de-482d-855f-0c29bd3adab1.png) Thank you so much for your guidance! Lan Nguyen

it should not have any problems running using jupyter notebook.  I have not tested on google colab yet.

**Comment by nguye2tl** [comment]
Hi Edwin,
Thank you for getting back to me. I am able to run the code pretty smooth now. Appreciate your help very much.
