### ISSUE TITLE
Adstock functionality

### ISSUE THREAD

**Issue by nguye2tl** [edwinnglabs/karpiu#60]
Hi Edwin,
Just want thank you so much again for sharing your knowledge and your remarkable work here. I want to ask a quick question about adstock functionality and I wonder whether I am making the right step here. I want to test with an excel file dataset and I am using the function make_adstock_metric to create adstock but I kept running into issues. Do you have any issues create adstock with a different dataset (an actual database in csv)? Which function do you suggest me to create for adstock process if you don't mind me asking.
Apologies for the inconvenience. I appreciate your great insights and valuable guidance as I am learning through this great package.
Greatly appreciate your time and patience,
Sincerely,
Lan Nguyen

**Comment by edwinnglabs** [comment]
hi @nguye2tl  you can take a look on the [source code](https://github.com/edwinnglabs/karpiu/blob/dev-net-profit-optim-clean/karpiu/simulation.py) how I parametrize adstock.
